/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicios.swing.ej3;

/**
 *
 * @author santi
 */
public class SelectorDeLenguajes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SelectorDeLenguajes.class.getName());

    /**
     * Creates new form SelectorDeLenguajes
     */
    public SelectorDeLenguajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaLenguajes = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] lenguajes = { "Java", "Python", "C++", "JavaScript", "C#" };
            public int getSize() { return lenguajes.length; }
            public String getElementAt(int i) { return lenguajes[i]; }
        }
    );
    listaLenguajes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            listaLenguajesMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(listaLenguajes);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(157, 157, 157))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(135, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaLenguajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaLenguajesMouseClicked
        if (evt.getClickCount() == 2) {
        String seleccionado = listaLenguajes.getSelectedValue();
        if (seleccionado != null) {
            mostrarInfo(seleccionado);
        }
    }
    }//GEN-LAST:event_listaLenguajesMouseClicked
    private void mostrarInfo(String lenguaje) {
    String info = switch (lenguaje) {
        case "Java" -> "Lenguaje orientado a objetos, multiplataforma, usado en Android y backend.";
        case "Python" -> "Lenguaje interpretado, ideal para IA, análisis de datos y desarrollo rápido.";
        case "C++" -> "Lenguaje compilado, potente y rápido, usado en videojuegos y sistemas embebidos.";
        case "JavaScript" -> "Lenguaje del navegador y también de backend (Node.js).";
        case "C#" -> "Lenguaje de Microsoft, usado en aplicaciones .NET y videojuegos (Unity).";
        default -> "Información no disponible.";
    };
    
    javax.swing.JOptionPane.showMessageDialog(this, info, lenguaje, javax.swing.JOptionPane.INFORMATION_MESSAGE);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SelectorDeLenguajes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaLenguajes;
    // End of variables declaration//GEN-END:variables
}
